"""add children + child_birth_conditions (CR)

Revision ID: 06ebd51c1ea1
Revises: ca8d5c613ff5
Create Date: 2026-07-13 14:29:17.504844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ebd51c1ea1'
down_revision: Union[str, Sequence[str], None] = 'ca8d5c613ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_uid', sa.String(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('babies_born', sa.String(), nullable=True),
    sa.Column('adoption_date', sa.Date(), nullable=True),
    sa.Column('child_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('birth_weight', sa.Float(), nullable=True),
    sa.Column('birth_length', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('previous_living_children', sa.Integer(), nullable=True),
    sa.Column('delivery_method', sa.String(), nullable=True),
    sa.Column('delivery_place', sa.String(), nullable=True),
    sa.Column('delivery_place_other', sa.String(), nullable=True),
    sa.Column('bf_within_one_hour', sa.Boolean(), nullable=True),
    sa.Column('ebf_during_stay', sa.Boolean(), nullable=True),
    sa.Column('ebf_reason', sa.String(), nullable=True),
    sa.Column('pre_existing_other', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_child_uid'), 'children', ['child_uid'], unique=True)
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('child_birth_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'condition', name='uq_child_condition')
    )
    op.create_index(op.f('ix_child_birth_conditions_id'), 'child_birth_conditions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_child_birth_conditions_id'), table_name='child_birth_conditions')
    op.drop_table('child_birth_conditions')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_index(op.f('ix_children_child_uid'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
