"""add children.bf_reason

Revision ID: 07f83433877c
Revises: 86f85c40fff5
Create Date: 2026-08-02 23:28:53.671449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f83433877c'
down_revision: Union[str, Sequence[str], None] = '86f85c40fff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('bf_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'bf_reason')
    # ### end Alembic commands ###
