"""learner category

Revision ID: 113e5337d31a
Revises: aa0f22f7722c
Create Date: 2026-08-10 19:25:27.499972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113e5337d31a'
down_revision: Union[str, Sequence[str], None] = 'aa0f22f7722c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('learner_category', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_learner_category'), 'users', ['learner_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_learner_category'), table_name='users')
    op.drop_column('users', 'learner_category')
    # ### end Alembic commands ###
