"""form_response mother_id + nullable child_id

Revision ID: 3a97143974dd
Revises: e7a41c9f52b8
Create Date: 2026-07-22 10:49:51.747368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a97143974dd'
down_revision: Union[str, Sequence[str], None] = 'e7a41c9f52b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_responses', sa.Column('mother_id', sa.Integer(), nullable=True))
    op.alter_column('form_responses', 'child_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_form_responses_mother_form', 'form_responses', ['mother_id', 'form_key'], unique=False)
    # Name the FK explicitly — autogenerate leaves it None, which breaks downgrade().
    op.create_foreign_key(
        'form_responses_mother_id_fkey', 'form_responses', 'mothers',
        ['mother_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('form_responses_mother_id_fkey', 'form_responses', type_='foreignkey')
    op.drop_index('ix_form_responses_mother_form', table_name='form_responses')
    # Mother-level responses have child_id = NULL; they cannot exist once child_id
    # is NOT NULL again, so drop them before re-imposing the constraint (otherwise
    # SET NOT NULL aborts on Postgres).
    op.execute("DELETE FROM form_responses WHERE child_id IS NULL")
    op.alter_column('form_responses', 'child_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('form_responses', 'mother_id')
    # ### end Alembic commands ###
