"""pipeline runs and scripts

Revision ID: 46c6ee821ffa
Revises: c41f6a2be703
Create Date: 2026-08-06 14:33:31.192636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c6ee821ffa'
down_revision: Union[str, Sequence[str], None] = 'c41f6a2be703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('run_dir', sa.String(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline'), 'pipeline_runs', ['pipeline'], unique=False)
    op.create_index('ix_pipeline_runs_pipeline_variant', 'pipeline_runs', ['pipeline', 'variant'], unique=False)
    op.create_table('pipeline_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline', 'slot', 'version', name='uq_pipeline_scripts_slot_version')
    )
    op.create_index(op.f('ix_pipeline_scripts_id'), 'pipeline_scripts', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_scripts_pipeline'), 'pipeline_scripts', ['pipeline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_scripts_pipeline'), table_name='pipeline_scripts')
    op.drop_index(op.f('ix_pipeline_scripts_id'), table_name='pipeline_scripts')
    op.drop_table('pipeline_scripts')
    op.drop_index('ix_pipeline_runs_pipeline_variant', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
