"""test shuffle options + question topic classification

Revision ID: 6475cb7b2cf4
Revises: f49dcd0d8f64
Create Date: 2026-09-09 11:35:58.387231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6475cb7b2cf4'
down_revision: Union[str, Sequence[str], None] = 'f49dcd0d8f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Question classification: which topic / subtopic a question examines, so
    # results can say WHERE a cohort is weak rather than only how much.
    op.add_column('questions', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('subtopic', sa.String(), nullable=True))
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)

    # Per-test randomisation. NOT NULL on an already-populated table, so the
    # rows that exist need a value: add with a server default to backfill them,
    # then drop the default so the column matches the ORM (which supplies its
    # own default on insert).
    op.add_column('tests', sa.Column('shuffle_questions', sa.Boolean(),
                                     nullable=False, server_default=sa.false()))
    op.add_column('tests', sa.Column('shuffle_options', sa.Boolean(),
                                     nullable=False, server_default=sa.false()))
    op.alter_column('tests', 'shuffle_questions', server_default=None)
    op.alter_column('tests', 'shuffle_options', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'shuffle_options')
    op.drop_column('tests', 'shuffle_questions')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_column('questions', 'subtopic')
    op.drop_column('questions', 'topic')
    # ### end Alembic commands ###
