"""pwa offline and push support

Revision ID: 6ce56e548ea1
Revises: 46c6ee821ffa
Create Date: 2026-08-09 01:04:04.274030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce56e548ea1'
down_revision: Union[str, Sequence[str], None] = '46c6ee821ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='push_subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.add_column('children', sa.Column('client_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_children_client_ref'), 'children', ['client_ref'], unique=True)
    op.add_column('form_responses', sa.Column('client_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_form_responses_client_ref'), 'form_responses', ['client_ref'], unique=True)
    op.add_column('mothers', sa.Column('client_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_mothers_client_ref'), 'mothers', ['client_ref'], unique=True)
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'link')
    op.drop_index(op.f('ix_mothers_client_ref'), table_name='mothers')
    op.drop_column('mothers', 'client_ref')
    op.drop_index(op.f('ix_form_responses_client_ref'), table_name='form_responses')
    op.drop_column('form_responses', 'client_ref')
    op.drop_index(op.f('ix_children_client_ref'), table_name='children')
    op.drop_column('children', 'client_ref')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
