"""LR extension: professional-axis master data + user fields

Revision ID: a83e5e58f049
Revises: 0c6205329832
Create Date: 2026-07-12 14:01:20.991931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83e5e58f049'
down_revision: Union[str, Sequence[str], None] = '0c6205329832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('facility_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_types_id'), 'facility_types', ['id'], unique=False)
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=False)
    op.create_table('designation_facility_types',
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('facility_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facility_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('designation_id', 'facility_type_id')
    )
    op.add_column('educational_qualifications', sa.Column('department_id', sa.Integer(), nullable=True))
    # NOT NULL on an existing table: backfill existing rows via server_default, then drop it to match the model.
    op.add_column('educational_qualifications', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('educational_qualifications', 'order_index', server_default=None)
    op.create_foreign_key('educational_qualifications_department_id_fkey', 'educational_qualifications', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('designation_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('facility_type_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('department_other', sa.String(), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_children', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('number_children', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('residence_distance_km', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('years_service', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('years_designation', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('years_facility', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('internet_workplace', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nutrition_training', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pregnancy_nutrition_training', sa.String(), nullable=True))
    op.add_column('users', sa.Column('breastfeeding_training', sa.String(), nullable=True))
    op.add_column('users', sa.Column('complementary_feeding_training', sa.String(), nullable=True))
    op.add_column('users', sa.Column('growth_monitoring_training', sa.String(), nullable=True))
    op.create_foreign_key('users_designation_id_fkey', 'users', 'designations', ['designation_id'], ['id'])
    op.create_foreign_key('users_facility_type_id_fkey', 'users', 'facility_types', ['facility_type_id'], ['id'])
    op.create_foreign_key('users_department_id_fkey', 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_facility_type_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_designation_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'growth_monitoring_training')
    op.drop_column('users', 'complementary_feeding_training')
    op.drop_column('users', 'breastfeeding_training')
    op.drop_column('users', 'pregnancy_nutrition_training')
    op.drop_column('users', 'nutrition_training')
    op.drop_column('users', 'internet_workplace')
    op.drop_column('users', 'years_facility')
    op.drop_column('users', 'years_designation')
    op.drop_column('users', 'years_service')
    op.drop_column('users', 'residence_distance_km')
    op.drop_column('users', 'number_children')
    op.drop_column('users', 'has_children')
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'department_other')
    op.drop_column('users', 'facility_type_id')
    op.drop_column('users', 'designation_id')
    op.drop_column('users', 'department_id')
    op.drop_constraint('educational_qualifications_department_id_fkey', 'educational_qualifications', type_='foreignkey')
    op.drop_column('educational_qualifications', 'order_index')
    op.drop_column('educational_qualifications', 'department_id')
    op.drop_table('designation_facility_types')
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_facility_types_id'), table_name='facility_types')
    op.drop_table('facility_types')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
