"""perf indexes + answer unique constraint

Revision ID: c1d1b325a402
Revises: c3f1a9b8e2d7
Create Date: 2026-07-17 12:06:09.288338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d1b325a402'
down_revision: Union[str, Sequence[str], None] = 'c3f1a9b8e2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.create_index(op.f('ix_stages_program_district_id'), 'stages', ['program_district_id'], unique=False)
    op.create_index(op.f('ix_test_answers_attempt_id'), 'test_answers', ['attempt_id'], unique=False)
    op.create_unique_constraint('uq_answer_attempt_question', 'test_answers', ['attempt_id', 'question_id'])
    op.create_index('ix_test_attempts_user_test', 'test_attempts', ['user_id', 'test_id'], unique=False)
    op.create_index(op.f('ix_tests_stage_id'), 'tests', ['stage_id'], unique=False)
    op.create_index(op.f('ix_tutorial_questions_tutorial_id'), 'tutorial_questions', ['tutorial_id'], unique=False)
    op.create_index('ix_tutorial_quiz_responses_user_tutorial', 'tutorial_quiz_responses', ['user_id', 'tutorial_id'], unique=False)
    op.create_index(op.f('ix_tutorials_stage_id'), 'tutorials', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorials_stage_id'), table_name='tutorials')
    op.drop_index('ix_tutorial_quiz_responses_user_tutorial', table_name='tutorial_quiz_responses')
    op.drop_index(op.f('ix_tutorial_questions_tutorial_id'), table_name='tutorial_questions')
    op.drop_index(op.f('ix_tests_stage_id'), table_name='tests')
    op.drop_index('ix_test_attempts_user_test', table_name='test_attempts')
    op.drop_constraint('uq_answer_attempt_question', 'test_answers', type_='unique')
    op.drop_index(op.f('ix_test_answers_attempt_id'), table_name='test_answers')
    op.drop_index(op.f('ix_stages_program_district_id'), table_name='stages')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    # ### end Alembic commands ###
