"""mother registration schema

Revision ID: ca8d5c613ff5
Revises: d94d52335d36
Create Date: 2026-07-13 13:32:47.058516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8d5c613ff5'
down_revision: Union[str, Sequence[str], None] = 'd94d52335d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_fields_id'), 'education_fields', ['id'], unique=False)
    op.create_table('mother_education_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('requires_field', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mother_education_levels_id'), 'mother_education_levels', ['id'], unique=False)
    op.create_table('education_degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['education_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_degrees_id'), 'education_degrees', ['id'], unique=False)
    op.create_table('phcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phcs_id'), 'phcs', ['id'], unique=False)
    op.create_table('hwcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('phc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phc_id'], ['phcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hwcs_id'), 'hwcs', ['id'], unique=False)
    op.create_table('mothers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_uid', sa.String(), nullable=False),
    sa.Column('registered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=False),
    sa.Column('adoption_date', sa.Date(), nullable=True),
    sa.Column('mother_dob', sa.Date(), nullable=True),
    sa.Column('mother_age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('lmp', sa.Date(), nullable=True),
    sa.Column('edd_lmp', sa.Date(), nullable=True),
    sa.Column('edd_records', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('alternate_mobile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('taluk_id', sa.Integer(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('hwc_id', sa.Integer(), nullable=True),
    sa.Column('phc_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('education_field_id', sa.Integer(), nullable=True),
    sa.Column('education_degree_id', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('occupation_other', sa.String(), nullable=True),
    sa.Column('ration_card', sa.String(), nullable=True),
    sa.Column('social_category', sa.String(), nullable=True),
    sa.Column('nutrition_course', sa.Boolean(), nullable=True),
    sa.Column('nutrition_course_name', sa.String(), nullable=True),
    sa.Column('video_frequency', sa.String(), nullable=True),
    sa.Column('implement_video', sa.String(), nullable=True),
    sa.Column('confidence_video', sa.String(), nullable=True),
    sa.Column('willingness_hcw', sa.String(), nullable=True),
    sa.Column('information_seeking', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['education_degree_id'], ['education_degrees.id'], ),
    sa.ForeignKeyConstraint(['education_field_id'], ['education_fields.id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['mother_education_levels.id'], ),
    sa.ForeignKeyConstraint(['hwc_id'], ['hwcs.id'], ),
    sa.ForeignKeyConstraint(['phc_id'], ['phcs.id'], ),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['taluk_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mothers_id'), 'mothers', ['id'], unique=False)
    op.create_index(op.f('ix_mothers_mother_uid'), 'mothers', ['mother_uid'], unique=True)
    op.create_table('mother_source_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=True),
    sa.Column('willingness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mother_id', 'source', name='uq_mother_source')
    )
    op.create_index(op.f('ix_mother_source_ratings_id'), 'mother_source_ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mother_source_ratings_id'), table_name='mother_source_ratings')
    op.drop_table('mother_source_ratings')
    op.drop_index(op.f('ix_mothers_mother_uid'), table_name='mothers')
    op.drop_index(op.f('ix_mothers_id'), table_name='mothers')
    op.drop_table('mothers')
    op.drop_index(op.f('ix_hwcs_id'), table_name='hwcs')
    op.drop_table('hwcs')
    op.drop_index(op.f('ix_phcs_id'), table_name='phcs')
    op.drop_table('phcs')
    op.drop_index(op.f('ix_education_degrees_id'), table_name='education_degrees')
    op.drop_table('education_degrees')
    op.drop_index(op.f('ix_mother_education_levels_id'), table_name='mother_education_levels')
    op.drop_table('mother_education_levels')
    op.drop_index(op.f('ix_education_fields_id'), table_name='education_fields')
    op.drop_table('education_fields')
    # ### end Alembic commands ###
