"""integrate tutorial-tracking and live-monitoring schema

Revision ID: d94d52335d36
Revises: a83e5e58f049
Create Date: 2026-07-13 01:31:08.560286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94d52335d36'
down_revision: Union[str, Sequence[str], None] = 'a83e5e58f049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_questions_id'), 'tutorial_questions', ['id'], unique=False)
    op.create_table('tutorial_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['tutorial_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_question_options_id'), 'tutorial_question_options', ['id'], unique=False)
    op.create_table('face_to_face_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_district_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_district_id'], ['program_districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_face_to_face_selections_id'), 'face_to_face_selections', ['id'], unique=False)
    op.create_table('tutorial_quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['tutorial_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['tutorial_question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_quiz_responses_id'), 'tutorial_quiz_responses', ['id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('device_fingerprint', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_question', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('questions_attempted', sa.Integer(), nullable=True),
    sa.Column('questions_unanswered', sa.Integer(), nullable=True),
    sa.Column('questions_viewed', sa.Integer(), nullable=True),
    sa.Column('questions_skipped', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('wrong_answers', sa.Integer(), nullable=True),
    sa.Column('accuracy_pct', sa.Float(), nullable=True),
    sa.Column('test_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_time_per_question_ms', sa.Integer(), nullable=True),
    sa.Column('fastest_question_ms', sa.Integer(), nullable=True),
    sa.Column('slowest_question_ms', sa.Integer(), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), nullable=True),
    sa.Column('fullscreen_exit_count', sa.Integer(), nullable=True),
    sa.Column('window_blur_count', sa.Integer(), nullable=True),
    sa.Column('copy_paste_count', sa.Integer(), nullable=True),
    sa.Column('idle_periods', sa.Integer(), nullable=True),
    sa.Column('question_switch_count', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('navigation_pattern', sa.JSON(), nullable=True),
    sa.Column('answer_state', sa.JSON(), nullable=True),
    sa.Column('last_sequence', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_live_sessions_id'), 'live_sessions', ['id'], unique=False)
    op.create_index('ix_live_sessions_risk', 'live_sessions', ['test_id', 'risk_score'], unique=False)
    op.create_index('ix_live_sessions_test_id_status', 'live_sessions', ['test_id', 'status'], unique=False)
    op.create_index('ix_live_sessions_user_test', 'live_sessions', ['user_id', 'test_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_id'), 'activity_events', ['id'], unique=False)
    op.create_index('ix_activity_events_session_ts', 'activity_events', ['session_id', 'timestamp'], unique=False)
    op.create_index('ix_activity_events_session_type', 'activity_events', ['session_id', 'event_type'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_id'), 'admin_actions', ['id'], unique=False)
    op.create_index('ix_admin_actions_session', 'admin_actions', ['session_id', 'timestamp'], unique=False)
    op.create_table('suspicious_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('risk_contribution', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_flags_id'), 'suspicious_flags', ['id'], unique=False)
    op.create_index('ix_suspicious_flags_session', 'suspicious_flags', ['session_id', 'detected_at'], unique=False)
    op.add_column('stages', sa.Column('stage_type', sa.String(), nullable=False, server_default='tutorials'))
    op.add_column('stages', sa.Column('quiz_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('tests', sa.Column('status', sa.String(), nullable=False, server_default='draft'))
    op.add_column('tests', sa.Column('test_type', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tutorials', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('tutorials', sa.Column('start_seconds', sa.Integer(), nullable=True))
    op.add_column('tutorials', sa.Column('end_seconds', sa.Integer(), nullable=True))
    op.add_column('tutorials', sa.Column('quiz_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_tutorial_progress', sa.Column('watch_time_seconds', sa.Float(), nullable=False, server_default='0'))
    op.add_column('user_tutorial_progress', sa.Column('watch_pct', sa.Float(), nullable=False, server_default='0'))
    op.add_column('user_tutorial_progress', sa.Column('last_position_seconds', sa.Float(), nullable=False, server_default='0'))
    op.add_column('user_tutorial_progress', sa.Column('video_duration_seconds', sa.Float(), nullable=True))
    op.add_column('user_tutorial_progress', sa.Column('quiz_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('user_tutorial_progress', sa.Column('quiz_score', sa.Float(), nullable=True))
    op.add_column('user_tutorial_progress', sa.Column('quiz_total', sa.Integer(), nullable=True))
    op.add_column('user_tutorial_progress', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_user_tutorial', 'user_tutorial_progress', ['user_id', 'tutorial_id'])
    # Drop the backfill server_defaults so columns match the ORM (python-side defaults only).
    op.alter_column('stages', 'stage_type', server_default=None)
    op.alter_column('stages', 'quiz_enabled', server_default=None)
    op.alter_column('tests', 'status', server_default=None)
    op.alter_column('tutorials', 'quiz_enabled', server_default=None)
    op.alter_column('user_tutorial_progress', 'watch_time_seconds', server_default=None)
    op.alter_column('user_tutorial_progress', 'watch_pct', server_default=None)
    op.alter_column('user_tutorial_progress', 'last_position_seconds', server_default=None)
    op.alter_column('user_tutorial_progress', 'quiz_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_tutorial', 'user_tutorial_progress', type_='unique')
    op.drop_column('user_tutorial_progress', 'updated_at')
    op.drop_column('user_tutorial_progress', 'quiz_total')
    op.drop_column('user_tutorial_progress', 'quiz_score')
    op.drop_column('user_tutorial_progress', 'quiz_status')
    op.drop_column('user_tutorial_progress', 'video_duration_seconds')
    op.drop_column('user_tutorial_progress', 'last_position_seconds')
    op.drop_column('user_tutorial_progress', 'watch_pct')
    op.drop_column('user_tutorial_progress', 'watch_time_seconds')
    op.drop_column('tutorials', 'quiz_enabled')
    op.drop_column('tutorials', 'end_seconds')
    op.drop_column('tutorials', 'start_seconds')
    op.drop_column('tutorials', 'youtube_url')
    op.drop_column('tests', 'ended_at')
    op.drop_column('tests', 'started_at')
    op.drop_column('tests', 'scheduled_at')
    op.drop_column('tests', 'test_type')
    op.drop_column('tests', 'status')
    op.drop_column('stages', 'quiz_enabled')
    op.drop_column('stages', 'stage_type')
    op.drop_index('ix_suspicious_flags_session', table_name='suspicious_flags')
    op.drop_index(op.f('ix_suspicious_flags_id'), table_name='suspicious_flags')
    op.drop_table('suspicious_flags')
    op.drop_index('ix_admin_actions_session', table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_id'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index('ix_activity_events_session_type', table_name='activity_events')
    op.drop_index('ix_activity_events_session_ts', table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_live_sessions_user_test', table_name='live_sessions')
    op.drop_index('ix_live_sessions_test_id_status', table_name='live_sessions')
    op.drop_index('ix_live_sessions_risk', table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_tutorial_quiz_responses_id'), table_name='tutorial_quiz_responses')
    op.drop_table('tutorial_quiz_responses')
    op.drop_index(op.f('ix_face_to_face_selections_id'), table_name='face_to_face_selections')
    op.drop_table('face_to_face_selections')
    op.drop_index(op.f('ix_tutorial_question_options_id'), table_name='tutorial_question_options')
    op.drop_table('tutorial_question_options')
    op.drop_index(op.f('ix_tutorial_questions_id'), table_name='tutorial_questions')
    op.drop_table('tutorial_questions')
    # ### end Alembic commands ###
