"""data protection layer

Adds the tables that let NurtureHUB answer for the patient data it holds, as
required by the data-privacy clause of the Maharashtra MOU and by the DPDP Act
2023 / CERT-In Directions 2022 it points at:

  audit_events, audit_anchors     hash-chained record of every access to a
                                  patient record, with truncation detection
  auth_sessions                   revocable server-side sessions, so a stolen
                                  or suspect token can actually be taken away
  login_attempts, account_lockouts brute-force and credential-stuffing defence
  mfa_enrollments, password_history  administrator account protection
  security_alerts                 what the detection rules noticed
  breach_incidents,
  breach_notifications            the breach register and its statutory clocks
  consent_records                 DPDP s.6 / s.9 consent, per purpose
  processing_activities           record of processing activities
  data_subject_requests,
  erasure_records                 DPDP ss.11-14 rights, and proof of deletion
  retention_policies              the retention schedule the sweeper reads

It also adds `mothers.mobile_lookup` and `users.phone_lookup`: keyed one-way
blind indexes that keep exact-match lookup working now that the corresponding
contact columns are encrypted at rest.

The contact columns themselves need no DDL — `EncryptedString` is a
TypeDecorator over the same TEXT storage, and reads tolerate plaintext, so
existing rows keep working until `scripts/encrypt_phi.py` seals them.

Revision ID: f49dcd0d8f64
Revises: d5b71a3c9f04
Create Date: 2026-08-27 19:32:12.410999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49dcd0d8f64'
down_revision: Union[str, Sequence[str], None] = 'd5b71a3c9f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_lockouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.String(length=320), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_lockouts_locked_until'), 'account_lockouts', ['locked_until'], unique=False)
    op.create_index(op.f('ix_account_lockouts_principal'), 'account_lockouts', ['principal'], unique=False)
    op.create_table('audit_anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chain_key', sa.String(length=96), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('last_entry_hash', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('prev_anchor_hash', sa.String(length=64), nullable=False),
    sa.Column('anchor_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_anchors_chain_key'), 'audit_anchors', ['chain_key'], unique=False)
    op.create_index(op.f('ix_audit_anchors_created_at'), 'audit_anchors', ['created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('session_jti', sa.String(length=64), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('forwarded_for', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('is_phi', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('chain_key', sa.String(length=96), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_key', 'sequence', name='uq_audit_chain_sequence')
    )
    op.create_index('ix_audit_actor_time', 'audit_events', ['actor_label', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_label'), 'audit_events', ['actor_label'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_events_chain_key'), 'audit_events', ['chain_key'], unique=False)
    op.create_index(op.f('ix_audit_events_is_phi'), 'audit_events', ['is_phi'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_outcome'), 'audit_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_session_jti'), 'audit_events', ['session_jti'], unique=False)
    op.create_index(op.f('ix_audit_events_source_ip'), 'audit_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_audit_events_subject_id'), 'audit_events', ['subject_id'], unique=False)
    op.create_index(op.f('ix_audit_events_subject_type'), 'audit_events', ['subject_type'], unique=False)
    op.create_index('ix_audit_phi_time', 'audit_events', ['is_phi', 'occurred_at'], unique=False)
    op.create_index('ix_audit_subject_time', 'audit_events', ['subject_type', 'subject_id', 'occurred_at'], unique=False)
    op.create_table('breach_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custody_party', sa.String(length=32), nullable=False),
    sa.Column('custody_rationale', sa.Text(), nullable=True),
    sa.Column('controlling_system', sa.String(length=255), nullable=True),
    sa.Column('fault_assessment', sa.Text(), nullable=True),
    sa.Column('joint_process', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('affected_subject_count', sa.Integer(), nullable=True),
    sa.Column('affected_subject_ids', sa.Text(), nullable=True),
    sa.Column('phi_involved', sa.Boolean(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(length=320), nullable=True),
    sa.Column('owner', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_incidents_custody_party'), 'breach_incidents', ['custody_party'], unique=False)
    op.create_index(op.f('ix_breach_incidents_reference'), 'breach_incidents', ['reference'], unique=True)
    op.create_index(op.f('ix_breach_incidents_severity'), 'breach_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_breach_incidents_status'), 'breach_incidents', ['status'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_type', sa.String(length=24), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_identifier', sa.String(length=255), nullable=True),
    sa.Column('requested_by', sa.String(length=160), nullable=True),
    sa.Column('requester_relationship', sa.String(length=64), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('handled_by', sa.String(length=320), nullable=True),
    sa.Column('response_ref', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_created_at'), 'data_subject_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_due_at'), 'data_subject_requests', ['due_at'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_reference'), 'data_subject_requests', ['reference'], unique=True)
    op.create_index(op.f('ix_data_subject_requests_request_type'), 'data_subject_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_status'), 'data_subject_requests', ['status'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_subject_id'), 'data_subject_requests', ['subject_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('principal', sa.String(length=320), nullable=False),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index('ix_login_attempts_ip_time', 'login_attempts', ['source_ip', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_principal'), 'login_attempts', ['principal'], unique=False)
    op.create_index('ix_login_attempts_principal_time', 'login_attempts', ['principal', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_source_ip'), 'login_attempts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_login_attempts_successful'), 'login_attempts', ['successful'], unique=False)
    op.create_table('mfa_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.String(length=320), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_step', sa.Integer(), nullable=True),
    sa.Column('recovery_codes', sa.Text(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_enrollments_principal'), 'mfa_enrollments', ['principal'], unique=True)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_principal'), 'password_history', ['principal'], unique=False)
    op.create_table('processing_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('lawful_basis', sa.String(length=160), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('special_category', sa.Boolean(), nullable=False),
    sa.Column('subject_categories', sa.Text(), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('storage_location', sa.String(length=160), nullable=True),
    sa.Column('cross_border', sa.Boolean(), nullable=False),
    sa.Column('retention_months', sa.Integer(), nullable=True),
    sa.Column('retention_rationale', sa.Text(), nullable=True),
    sa.Column('security_measures', sa.Text(), nullable=True),
    sa.Column('controller', sa.String(length=160), nullable=True),
    sa.Column('processor', sa.String(length=160), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_activities_key'), 'processing_activities', ['key'], unique=True)
    op.create_table('retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('legal_basis', sa.String(length=255), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_rows', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_key'), 'retention_policies', ['key'], unique=True)
    op.create_table('breach_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('authority_label', sa.String(length=160), nullable=False),
    sa.Column('legal_basis', sa.String(length=255), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.String(length=320), nullable=True),
    sa.Column('not_applicable', sa.Boolean(), nullable=False),
    sa.Column('not_applicable_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['breach_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'authority', name='uq_incident_authority')
    )
    op.create_index(op.f('ix_breach_notifications_due_at'), 'breach_notifications', ['due_at'], unique=False)
    op.create_index(op.f('ix_breach_notifications_incident_id'), 'breach_notifications', ['incident_id'], unique=False)
    op.create_table('erasure_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_uid', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('rows_deleted', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=True),
    sa.Column('performed_by', sa.String(length=320), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['data_subject_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erasure_records_performed_at'), 'erasure_records', ['performed_at'], unique=False)
    op.create_index(op.f('ix_erasure_records_subject_id'), 'erasure_records', ['subject_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('audit_event_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=320), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['breach_incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_rule_actor_time', 'security_alerts', ['rule', 'actor_label', 'raised_at'], unique=False)
    op.create_index('ix_alerts_status_severity', 'security_alerts', ['status', 'severity', 'raised_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_actor_label'), 'security_alerts', ['actor_label'], unique=False)
    op.create_index(op.f('ix_security_alerts_raised_at'), 'security_alerts', ['raised_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_rule'), 'security_alerts', ['rule'], unique=False)
    op.create_index(op.f('ix_security_alerts_severity'), 'security_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_security_alerts_status'), 'security_alerts', ['status'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('principal', sa.String(length=320), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('revoked_by', sa.String(length=320), nullable=True),
    sa.Column('mfa_satisfied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_device_hash'), 'auth_sessions', ['device_hash'], unique=False)
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_is_admin'), 'auth_sessions', ['is_admin'], unique=False)
    op.create_index(op.f('ix_auth_sessions_jti'), 'auth_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_auth_sessions_principal'), 'auth_sessions', ['principal'], unique=False)
    op.create_index('ix_auth_sessions_principal_active', 'auth_sessions', ['principal', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('notice_version', sa.String(length=32), nullable=False),
    sa.Column('notice_language', sa.String(length=16), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('given_by', sa.String(length=160), nullable=True),
    sa.Column('given_by_relationship', sa.String(length=64), nullable=True),
    sa.Column('is_guardian_consent', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=64), nullable=True),
    sa.Column('captured_by_user_id', sa.Integer(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['captured_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'purpose', name='uq_consent_subject_purpose')
    )
    op.create_index(op.f('ix_consent_records_purpose'), 'consent_records', ['purpose'], unique=False)
    op.create_index(op.f('ix_consent_records_subject_id'), 'consent_records', ['subject_id'], unique=False)
    op.create_index(op.f('ix_consent_records_subject_type'), 'consent_records', ['subject_type'], unique=False)
    op.create_index(op.f('ix_consent_records_withdrawn_at'), 'consent_records', ['withdrawn_at'], unique=False)
    op.create_index('ix_consent_subject', 'consent_records', ['subject_type', 'subject_id'], unique=False)
    op.add_column('mothers', sa.Column('mobile_lookup', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_mothers_mobile_lookup'), 'mothers', ['mobile_lookup'], unique=False)
    op.add_column('users', sa.Column('phone_lookup', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_phone_lookup'), 'users', ['phone_lookup'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_lookup'), table_name='users')
    op.drop_column('users', 'phone_lookup')
    op.drop_index(op.f('ix_mothers_mobile_lookup'), table_name='mothers')
    op.drop_column('mothers', 'mobile_lookup')
    op.drop_index('ix_consent_subject', table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_withdrawn_at'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_subject_type'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_subject_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_purpose'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_principal_active', table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_principal'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_jti'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_is_admin'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_device_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_security_alerts_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_severity'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_rule'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_raised_at'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_actor_label'), table_name='security_alerts')
    op.drop_index('ix_alerts_status_severity', table_name='security_alerts')
    op.drop_index('ix_alerts_rule_actor_time', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_erasure_records_subject_id'), table_name='erasure_records')
    op.drop_index(op.f('ix_erasure_records_performed_at'), table_name='erasure_records')
    op.drop_table('erasure_records')
    op.drop_index(op.f('ix_breach_notifications_incident_id'), table_name='breach_notifications')
    op.drop_index(op.f('ix_breach_notifications_due_at'), table_name='breach_notifications')
    op.drop_table('breach_notifications')
    op.drop_index(op.f('ix_retention_policies_key'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_processing_activities_key'), table_name='processing_activities')
    op.drop_table('processing_activities')
    op.drop_index(op.f('ix_password_history_principal'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_mfa_enrollments_principal'), table_name='mfa_enrollments')
    op.drop_table('mfa_enrollments')
    op.drop_index(op.f('ix_login_attempts_successful'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_source_ip'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_principal_time', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_principal'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_ip_time', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_data_subject_requests_subject_id'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_status'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_request_type'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_reference'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_due_at'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_created_at'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_breach_incidents_status'), table_name='breach_incidents')
    op.drop_index(op.f('ix_breach_incidents_severity'), table_name='breach_incidents')
    op.drop_index(op.f('ix_breach_incidents_reference'), table_name='breach_incidents')
    op.drop_index(op.f('ix_breach_incidents_custody_party'), table_name='breach_incidents')
    op.drop_table('breach_incidents')
    op.drop_index('ix_audit_subject_time', table_name='audit_events')
    op.drop_index('ix_audit_phi_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_subject_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_subject_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_source_ip'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_session_jti'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_outcome'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_is_phi'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_chain_key'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_label'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_actor_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_audit_anchors_created_at'), table_name='audit_anchors')
    op.drop_index(op.f('ix_audit_anchors_chain_key'), table_name='audit_anchors')
    op.drop_table('audit_anchors')
    op.drop_index(op.f('ix_account_lockouts_principal'), table_name='account_lockouts')
    op.drop_index(op.f('ix_account_lockouts_locked_until'), table_name='account_lockouts')
    op.drop_table('account_lockouts')
    # ### end Alembic commands ###
